# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 12:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import warhammer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('race', models.CharField(choices=[('HUMAN', 'human'), ('DWARF', 'dwarf'), ('ELF', 'elf'), ('HALFLING', 'halfling')], default='HUMAN', max_length=16)),
                ('current_career', models.CharField(blank=True, max_length=32, null=True)),
                ('previous_career', models.CharField(blank=True, max_length=32, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.SmallIntegerField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], null=True)),
                ('eye_color', models.CharField(blank=True, max_length=16, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=16, null=True)),
                ('weight', models.SmallIntegerField(blank=True, null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('star_sign', models.CharField(blank=True, max_length=32, null=True)),
                ('number_of_siblings', models.SmallIntegerField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=32, null=True)),
                ('distinguishing_marks', models.CharField(blank=True, max_length=32, null=True)),
                ('weapon_skill', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ballistic_skill', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('strength', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('toughness', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('agility', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('intelligence', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('will_power', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fellowship', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attacks', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('wounds', models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('movement', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('magic', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('insanity_points', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('fate_points', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('portrait', models.ImageField(blank=True, null=True, upload_to=warhammer.models.get_image_path)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
