# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='previous_career',
            new_name='previous_careers',
        ),
    ]
