# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 20:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0002_auto_20180417_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='strength_bonus',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='hero',
            name='toughness_bonus',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
