# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0003_auto_20180417_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[('male', 'male'), ('female', 'female')], null=True),
        ),
    ]
