# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0004_auto_20180419_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(choices=[('human', 'human'), ('human', 'dwarf'), ('human', 'elf'), ('human', 'halfling')], default='human', max_length=16),
        ),
    ]
