# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0005_auto_20180419_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=16),
        ),
    ]
