# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 18:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0006_auto_20180419_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='portrait',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
